'use strict';
const S=window.BusSim,$=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let mode='B',state,timeline,timer=null;const node=id=>S.nodes.find(n=>n.id===id),name=id=>node(id)?.name??id;const fmt=t=>`${String(9+Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;
function stop(){clearInterval(timer);timer=null;$('play').textContent='▶ 再生'}
function reset(){stop();timeline=window.BusTimeline.create(Number($('seed').value)||42,mode);state=timeline.state;$('comparison').hidden=true;$('notice').textContent='再生して滞在が始まると、「あと30分」を試せます。';render()}
function advance(n){state=timeline.advance(n);if(state.time>=180)stop();render()}
function seek(minute){stop();state=timeline.seek(minute);render()}
function renderMap(){let out='<defs><pattern id="grid" width="22" height="22" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="#dbe4d5"/></pattern></defs><rect width="760" height="440" fill="url(#grid)"/><text x="26" y="28" font-size="10" fill="#9ba991" letter-spacing="2">FICTIONAL TOWN / 6 STOPS</text>';
for(const [a,b,d] of S.edges){const u=node(a),v=node(b);out+=`<line x1="${u.x}" y1="${u.y}" x2="${v.x}" y2="${v.y}" stroke="#e0e7da" stroke-width="14" stroke-linecap="round"/><line x1="${u.x}" y1="${u.y}" x2="${v.x}" y2="${v.y}" stroke="#fff" stroke-width="2" stroke-dasharray="5 6"/><text x="${(u.x+v.x)/2}" y="${(u.y+v.y)/2-9}" text-anchor="middle" fill="#99a390" font-size="10">${d}分</text>`}
for(const n of S.nodes){let f=S.forecast(n.id,state.time);if(typeof f==='object')f=f.expected??0;const r=18+Math.sqrt(Math.max(0,f))*19;out+=`<circle cx="${n.x}" cy="${n.y}" r="${r}" fill="#c8dda1" fill-opacity=".24" stroke="#b6ca95" stroke-dasharray="3 5"/><text x="${n.x}" y="${Math.min(n.y+50,432)}" text-anchor="middle" font-size="10" fill="#8c9e70">予測 ${Number(f).toFixed(1)}人</text>`}
state.buses.forEach((b,i)=>{const points=[b.edge?.to??b.node,...(b.route||[])].map(node).filter(Boolean);if(points.length>1)out+=`<polyline points="${points.map(n=>`${n.x},${n.y}`).join(' ')}" fill="none" stroke="${i?'#557daf':'#287959'}" stroke-width="3" stroke-opacity=".45" stroke-dasharray="6 5"/>`});
for(const n of S.nodes){const wait=state.people.filter(p=>p.kind==='walkin'&&p.status==='waiting'&&p.node===n.id).length;out+=`<circle cx="${n.x}" cy="${n.y}" r="12" fill="#fff" stroke="#8eaa87" stroke-width="3"/><circle cx="${n.x}" cy="${n.y}" r="4" fill="#60845b"/><text x="${n.x}" y="${n.y-23}" text-anchor="middle" font-size="14" font-weight="600" fill="#435941">${esc(n.name)}</text>`;if(wait)out+=`<g transform="translate(${n.x-75},${n.y+9})"><rect width="54" height="23" rx="11" fill="#f5d9b9"/><text x="27" y="16" text-anchor="middle" font-size="11" fill="#985c22">待ち ${wait}</text></g>`}
for(const n of S.nodes){
const waiting=state.people.filter(p=>p.kind==='registered'&&p.status==='waiting'&&p.node===n.id);
if(!waiting.length)continue;
const width=110,height=waiting.length*23+8,x=n.x>500?n.x-width-22:n.x+22,y=Math.max(35,Math.min(n.y-16,432-height));
out+=`<g class="registered-waiters" data-node="${esc(n.id)}" transform="translate(${x},${y})"><title>${esc(n.name)}で予約待機：${waiting.map(p=>esc(p.name)).join('、')}</title><rect width="${width}" height="${height}" rx="8" fill="#edf3ff" stroke="#7698c5"/>${waiting.map((p,i)=>`<g class="registered-waiter" data-person="${esc(p.id)}" transform="translate(8,${7+i*23})"><circle cx="6" cy="4" r="3" fill="#5279ad"/><path d="M2 15v-4a4 4 0 0 1 8 0v4" fill="#5279ad"/><text x="19" y="12" font-size="12" font-weight="600" fill="#365b8b">${esc(p.name)}</text></g>`).join('')}</g>`;
}
state.buses.forEach((b,i)=>{let n=node(b.node),x=n.x,y=n.y;if(b.edge){const u=node(b.edge.from),v=node(b.edge.to),p=Math.min(1,b.edge.elapsed/b.edge.duration);x=u.x+(v.x-u.x)*p;y=u.y+(v.y-u.y)*p}else{x+=i?19:-19;y+=17}out+=`<g transform="translate(${x-20},${y-11})"><rect width="40" height="23" rx="7" fill="${i?'#557daf':'#287959'}" stroke="white" stroke-width="2"/><text x="20" y="16" text-anchor="middle" fill="white" font-size="11" font-weight="700">${i+1} · ${b.onboard.length}</text></g>`});$('map').innerHTML=out}
const statuses={pending:'出発前',waiting:'迎え待ち',onboard:'乗車中',staying:'滞在中',done:'完了',missed:'未割当／期限超過'};
function render(){const m=S.metrics(state);$('modeA').classList.toggle('selected',mode==='A');$('modeB').classList.toggle('selected',mode==='B');$('modeTitle').textContent=mode==='A'?'A 予定のみ':'B 予定＋需要予測';$('clock').textContent=fmt(state.time);$('timeSlider').value=state.time;$('timeSlider').setAttribute('aria-valuetext',fmt(state.time));$('timeSlider').style.setProperty('--elapsed',`${state.time/180*100}%`);$('phase').textContent=state.time>=180?'12:00 最終結果':'途中経過';$('play').disabled=state.time>=180;$('step').disabled=state.time>=180;
$('stats').innerHTML=[['登録者の予定達成',m.registered,'/ 5人',true],['未予約者の移動達成',m.walkin,'/ 5人',true],['総走行距離',Number(m.distance).toFixed(1),'km',false]].map(([label,v,unit,bar])=>`<div class="stat"><div class="stat-label">${label}</div><div class="stat-value"><b>${v}</b><span>${unit}${bar?` · ${Number(v)*20}%`:''}</span></div>${bar?`<div class="bar"><div style="width:${Number(v)*20}%"></div></div>`:''}</div>`).join('');
$('busCards').innerHTML=state.buses.map((b,i)=>`<div class="bus-card"><b style="color:${i?'#557daf':'#287959'}">● バス${i+1}</b>${b.onboard.length} / 4席<br>${b.edge?`${esc(name(b.edge.from))} → ${esc(name(b.edge.to))}`:`${esc(name(b.node))} に停車`}<br><span class="muted" style="margin:0">次の経由地：${(b.route||[]).slice(0,4).map(x=>esc(name(x))).join(' → ')||'待機'}</span></div>`).join('');
$('logs').innerHTML=state.logs.slice(-8).reverse().map(l=>`<div>${esc(typeof l==='string'?l.replace(/^\[(\d+)\]/,(_,t)=>fmt(Number(t))):JSON.stringify(l))}</div>`).join('')||'<div>再生すると運行記録がここに表示されます。</div>';
$('people').innerHTML=state.people.filter(p=>p.kind==='registered').map(p=>`<article class="person"><h3>${esc(p.name||p.id)}</h3><span class="status">${p.unassigned&&['pending','waiting','staying'].includes(p.status)?'未割当':statuses[p.status]||esc(p.status)}</span><p>${[p.origin,...p.visits,p.origin].map(x=>esc(name(x))).join(' → ')}</p><div>帰着期限 ${fmt(p.deadline)}</div><div>${p.status==='staying'?`次の出発可能 ${fmt(p.readyAt)}`:`現在地 ${esc(p.status==='onboard'?'車内':name(p.node))}`}</div><button data-extend="${esc(p.id)}" ${p.status!=='staying'||state.time>=180?'disabled':''}>あと30分</button></article>`).join('');$('walkins').innerHTML=state.people.filter(p=>p.kind==='walkin').map(p=>`<div class="walkin"><b>${esc(p.name)}</b><span>${p.status==='pending'?'まだ発生していません':`${esc(name(p.origin))} → ${esc(name(p.destination))}`}</span><span class="status">${p.unassigned&&['pending','waiting','staying'].includes(p.status)?'未割当':statuses[p.status]||esc(p.status)}</span></div>`).join('');renderMap()}
$('people').addEventListener('click',e=>{const b=e.target.closest('[data-extend]');if(!b)return;stop();const r=timeline.extend(b.dataset.extend);state=timeline.state;$('notice').textContent=r.message+(r.ok?'。この時刻から先の運行を再計算します。':'');render()});
$('play').onclick=()=>{if(timer)return stop();$('play').textContent='Ⅱ 一時停止';timer=setInterval(()=>advance(Number($('speed').value)),180)};$('step').onclick=()=>{stop();advance(10)};$('reset').onclick=reset;$('modeA').onclick=()=>{mode='A';reset()};$('modeB').onclick=()=>{mode='B';reset()};
$('compare').onclick=()=>{stop();const seed=Number($('seed').value)||42;const a=S.create(seed,'A'),b=S.create(seed,'B');for(let i=0;i<180;i++){S.step(a);S.step(b)}const am=S.metrics(a),bm=S.metrics(b);const c=$('comparison');c.hidden=false;c.innerHTML=`<div class="panel-head"><b>同じ条件、2つの運行。</b><span class="tag">シード ${seed} / 予定変更なし / 12:00</span></div><table><thead><tr><th>評価指標</th><th>A 予定のみ</th><th>B ＋需要予測</th></tr></thead><tbody><tr><td>登録者の予定達成率</td><td>${am.registered*20}%（${am.registered}/5人）</td><td>${bm.registered*20}%（${bm.registered}/5人）</td></tr><tr><td>未予約者の移動達成率</td><td>${am.walkin*20}%（${am.walkin}/5人）</td><td>${bm.walkin*20}%（${bm.walkin}/5人）</td></tr><tr><td>総走行距離</td><td>${Number(am.distance).toFixed(1)} km</td><td>${Number(bm.distance).toFixed(1)} km</td></tr>${S.nodes.map(n=>`<tr><td>${esc(n.name)} 発の未予約・未達人数</td><td>${am.unmet[n.name]??am.unmet[n.id]??0}人</td><td>${bm.unmet[n.name]??bm.unmet[n.id]??0}人</td></tr>`).join('')}</tbody></table><p class="note">B−A：未予約の到着 ${bm.walkin-am.walkin>=0?'+':''}${bm.walkin-am.walkin}人 / 走行距離 ${(bm.distance-am.distance).toFixed(1)} km。現在の地図は比較実行前の状態を保持しています。未達人数には終了時点の乗車中・待機中・未発生を含みます。</p>`;c.scrollIntoView({behavior:'smooth',block:'start'})};
$('timeSlider').addEventListener('input',e=>seek(e.target.value));
reset();window.demo={get state(){return state},advance,seek,reset};
